### ISSUE TITLE
关于EntityFrameworkCore9不能适配

### ISSUE THREAD

**Issue by gimmickj** [dotnetcore/EntityFrameworkCore.KingbaseES#21]

**Comment by wangpengxpy** [comment]
最近我抽空适配下吧

**Comment by wangpengxpy** [comment]
[9.0.0已发布](https://www.nuget.org/packages/DotNetCore.EntityFrameworkCore.KingbaseES/9.0.0)

**Comment by hatzhang** [comment]
@wangpengxpy  9.0.0是使用了最新的官方驱动吗？  8.0版本的驱动有个性能问题。
我们在考虑要切换成官方的efcore，他带的那个驱动可以解决我们的性能问题。
但他有个datetime转换的问题。

**Comment by gimmickj** [comment]
对，我使用的最新efcore官方最新驱动




jielitodo
***@***.***

**Comment by wangpengxpy** [comment]
> @wangpengxpy 9.0.0是使用了最新的官方驱动吗？ 8.0版本的驱动有个性能问题。 我们在考虑要切换成官方的efcore，他带的那个驱动可以解决我们的性能问题。 但他有个datetime转换的问题。

是的，集成了官方最新驱动
