### ISSUE TITLE
大的DataTable写入时的性能问题

### ISSUE THREAD

**Issue by hatzhang** [dotnetcore/EntityFrameworkCore.KingbaseES#22]
使用8.0版本时，他带的驱动有个性能问题。就是在做DataSet merge时，其DataTable包含几万条数据时，写入时间会将近20分钟。

在切换成[官方的efcore](https://www.nuget.org/packages/Kdbndp.EntityFrameworkCore.KingbaseES_V9/)后，可以改善到至3分钟。

您这边8.0版本的驱动可以调整为[这个](https://www.nuget.org/packages/Kdbndp_V9/8.0.1.11)吗？

**Comment by hatzhang** [comment]
我上传了一个[kingbase docker镜像](https://hub.docker.com/repository/docker/bitmountain/kingbasev8r6)，您可以使用这个做测试.

**Comment by wangpengxpy** [comment]
9.0.0版本是使用官方上传的v9版本的Kdbndp.dll了，你测试验证下看看是否没问题，若你验证有问题，就上传个demo，我再验证下看看吧
