### ISSUE TITLE
V9版本 和 EFcore8支持情况咨询

### ISSUE THREAD

**Issue by zzwh** [dotnetcore/EntityFrameworkCore.KingbaseES#5]
1. 请问对人大金仓的V9版本会支持吗? 如果会, 大约什么时间开始支持?
2. EFcore8 即将正式 , 支持情况是怎样的?

**Comment by wangpengxpy** [comment]
据我所知V8也支持直接使用PG连接，V9理论上可以，你可以使用PG连接试试，若不行，我们可以考虑再适配

**Comment by wangpengxpy** [comment]
@zzwh 你好，下周我们会发布适配ef core 8.0的版本，V9和V8应该没什么区别，你可以先用适配的8.0 V8版本验证试试，具体情况只有反馈给到我们，我们才好做进一步处理哈

**Comment by wangpengxpy** [comment]
EF Core 8.0已发布，经大概测试同样也支持人大金仓V9版本
