### ISSUE TITLE
test项目不能创建数据库

### ISSUE THREAD

**Issue by guangmang** [dotnetcore/EntityFrameworkCore.KingbaseES#7]
context.Database.EnsureCreated(); 这行代码跟进去，
        var adminDb = Dependencies.ContextOptions.FindExtension<KdbndpOptionsExtension>()?.AdminDatabase
            ?? "postgres";
发现AdminDatabase为null。

请问test项目跑起来还需要什么操作？

**Comment by wangpengxpy** [comment]
自行创建数据库表，前提对EF Core基础有所了解，【var adminDb = Dependencies.ContextOptions.FindExtension()?.AdminDatabase
?? "postgres"】我没用过
