### ISSUE TITLE
linq StartWith函数sql语句有问题

### ISSUE THREAD

**Issue by jadonhuang** [dotnetcore/EntityFrameworkCore.KingbaseES#9]
WHERE (@__a_0 = '') OR (((b."SiteName" IS NOT NULL)) AND ((b."SiteName" LIKE @__a_0 || '%' ESCAPE '') AND (left(b."SiteName", length(@__a_0))::text = @__a_0::text)))

 ESCAPE 附近有语法错误，貌似是缺少括号 
应该是  (b."SiteName" LIKE @__a_0 || '%') ESCAPE ''

**Comment by wangpengxpy** [comment]
@jadonhuang 麻烦提供下DEMO示例

**Comment by wangpengxpy** [comment]
未提供进一步信息，此问题暂时关闭
